### ISSUE TITLE
Homepage and Contact Page

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#57]
On a phone - contact is by email, on a desktop contact is to request a cal back. 

On a phone the email browser opens when you click on it - I think for a phone it should also be request a call back. 

<img width="749" alt="Screen Shot 2019-12-16 at 11 06 21 am" src="https://user-images.githubusercontent.com/55725505/70871537-1f8c6f80-1ff4-11ea-9fb8-c90d77dae453.png">

Will check with Paul

**Comment by LaraStudioFriday** [comment]
Ok on a phone - 

Want to find out more?
Call us on +61 2 9690 1109
or request a call back

Phone 
Send button

On a desktop -

Want to find out more?
Call us on +61 2 9690 1109 (Mark can the number hyperlink)
or request a call back

Email
Send Button

**Comment by markendley** [comment]
done

**Comment by LaraStudioFriday** [comment]
on the http://marke2.sg-host.com/plumpspry/contact/ page

on a desktop - needs to change to email still showing phone

ALSO

on a phone (on contact page) can the number hyperlink?
